#!/bin/sh
set -e

BASH_COMPLETION_FILE="/usr/share/bash-completion/completions/ssh-connect"
ZSH_COMPLETION_FILE="/usr/share/zsh/vendor-completions/_ssh-connect"
FISH_COMPLETION_FILE="/usr/share/fish/vendor_completions.d/ssh-connect.fish"

case "$1" in
    remove|purge)
        rm -f "$BASH_COMPLETION_FILE" "$ZSH_COMPLETION_FILE" "$FISH_COMPLETION_FILE"
    ;;
esac

#DEBHELPER#

exit 0
